# https://taskfile.dev

version: '3'

tasks:
  build:
    deps:
      - task: test
    cmds:
      - go build -ldflags="-s -w" -o build/ ./cmd/distillation
    generates:
      - build/distillation
  clean:
    cmds:
      - rm -rf .task/
      - rm -rf build/
      - rm -rf pkg/distillation/distillationproto/*.pb.go
      - rm -rf pkg/process/mocks/*.go
  run:
    cmds:
      - go run ./cmd/distillation
    deps:
      - task: generate
  generate:
    cmds:
      - go generate ./...
    sources:
      - ./**/*.proto
      - ./**/mockgen*
    generates:
      - ./**/*.pb.go
      - ./**/*.mockgen.go
  test:
    deps:
      - task: generate
    cmds:
      - go test ./...
    sources:
      - ./**/*.go