# https://taskfile.dev

version: '3'

tasks:
  run:
    cmds:
      - go run ./cmd/distillation
  proto:
    cmds:
      - >
        protoc
        --go_out=.
        --go_opt=paths=source_relative
        --go-grpc_out=. --go-grpc_opt=paths=source_relative
        pkg/distillation/distillationproto/*.proto
  test:
    cmds:
     - go test ./...
