// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: wifi.proto

package osproto

import (
	reflect "reflect"
	sync "sync"

	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ssid *wrappers.StringValue `protobuf:"bytes,2,opt,name=ssid,proto3" json:"ssid,omitempty"`
}

func (x *AP) Reset() {
	*x = AP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wifi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AP) ProtoMessage() {}

func (x *AP) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AP.ProtoReflect.Descriptor instead.
func (*AP) Descriptor() ([]byte, []int) {
	return file_wifi_proto_rawDescGZIP(), []int{0}
}

func (x *AP) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AP) GetSsid() *wrappers.StringValue {
	if x != nil {
		return x.Ssid
	}
	return nil
}

type APReplies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ap []*AP `protobuf:"bytes,1,rep,name=ap,proto3" json:"ap,omitempty"`
}

func (x *APReplies) Reset() {
	*x = APReplies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wifi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APReplies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APReplies) ProtoMessage() {}

func (x *APReplies) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APReplies.ProtoReflect.Descriptor instead.
func (*APReplies) Descriptor() ([]byte, []int) {
	return file_wifi_proto_rawDescGZIP(), []int{1}
}

func (x *APReplies) GetAp() []*AP {
	if x != nil {
		return x.Ap
	}
	return nil
}

type Network struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ap       *AP                   `protobuf:"bytes,1,opt,name=ap,proto3" json:"ap,omitempty"`
	Password *wrappers.StringValue `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *Network) Reset() {
	*x = Network{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wifi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_wifi_proto_rawDescGZIP(), []int{2}
}

func (x *Network) GetAp() *AP {
	if x != nil {
		return x.Ap
	}
	return nil
}

func (x *Network) GetPassword() *wrappers.StringValue {
	if x != nil {
		return x.Password
	}
	return nil
}

type ConnectedReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Connected *wrappers.BoolValue   `protobuf:"bytes,1,opt,name=connected,proto3" json:"connected,omitempty"`
	Ssid      *wrappers.StringValue `protobuf:"bytes,2,opt,name=ssid,proto3" json:"ssid,omitempty"`
}

func (x *ConnectedReply) Reset() {
	*x = ConnectedReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wifi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedReply) ProtoMessage() {}

func (x *ConnectedReply) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedReply.ProtoReflect.Descriptor instead.
func (*ConnectedReply) Descriptor() ([]byte, []int) {
	return file_wifi_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectedReply) GetConnected() *wrappers.BoolValue {
	if x != nil {
		return x.Connected
	}
	return nil
}

func (x *ConnectedReply) GetSsid() *wrappers.StringValue {
	if x != nil {
		return x.Ssid
	}
	return nil
}

var File_wifi_proto protoreflect.FileDescriptor

var file_wifi_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x77, 0x69, 0x66, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70,
	0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x02, 0x41, 0x50, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x30, 0x0a, 0x04, 0x73, 0x73, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x73, 0x73, 0x69,
	0x64, 0x22, 0x20, 0x0a, 0x09, 0x41, 0x50, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x12, 0x13,
	0x0a, 0x02, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x03, 0x2e, 0x41, 0x50, 0x52,
	0x02, 0x61, 0x70, 0x22, 0x58, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x13,
	0x0a, 0x02, 0x61, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x03, 0x2e, 0x41, 0x50, 0x52,
	0x02, 0x61, 0x70, 0x12, 0x38, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x7c, 0x0a,
	0x0e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x38, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x30, 0x0a, 0x04, 0x73, 0x73, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x73, 0x73, 0x69, 0x64, 0x32, 0xda, 0x01, 0x0a, 0x04,
	0x57, 0x69, 0x66, 0x69, 0x12, 0x2b, 0x0a, 0x03, 0x41, 0x50, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x0a, 0x2e, 0x41, 0x50, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x22,
	0x00, 0x12, 0x3e, 0x0a, 0x0a, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x36, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0f, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x07, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x12, 0x08, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x6f, 0x73, 0x2f, 0x6f,
	0x73, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wifi_proto_rawDescOnce sync.Once
	file_wifi_proto_rawDescData = file_wifi_proto_rawDesc
)

func file_wifi_proto_rawDescGZIP() []byte {
	file_wifi_proto_rawDescOnce.Do(func() {
		file_wifi_proto_rawDescData = protoimpl.X.CompressGZIP(file_wifi_proto_rawDescData)
	})
	return file_wifi_proto_rawDescData
}

var file_wifi_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wifi_proto_goTypes = []interface{}{
	(*AP)(nil),                   // 0: AP
	(*APReplies)(nil),            // 1: APReplies
	(*Network)(nil),              // 2: Network
	(*ConnectedReply)(nil),       // 3: ConnectedReply
	(*wrappers.StringValue)(nil), // 4: google.protobuf.StringValue
	(*wrappers.BoolValue)(nil),   // 5: google.protobuf.BoolValue
	(*empty.Empty)(nil),          // 6: google.protobuf.Empty
}
var file_wifi_proto_depIdxs = []int32{
	4,  // 0: AP.ssid:type_name -> google.protobuf.StringValue
	0,  // 1: APReplies.ap:type_name -> AP
	0,  // 2: Network.ap:type_name -> AP
	4,  // 3: Network.password:type_name -> google.protobuf.StringValue
	5,  // 4: ConnectedReply.connected:type_name -> google.protobuf.BoolValue
	4,  // 5: ConnectedReply.ssid:type_name -> google.protobuf.StringValue
	6,  // 6: Wifi.APs:input_type -> google.protobuf.Empty
	6,  // 7: Wifi.Disconnect:input_type -> google.protobuf.Empty
	6,  // 8: Wifi.Connected:input_type -> google.protobuf.Empty
	2,  // 9: Wifi.Connect:input_type -> Network
	1,  // 10: Wifi.APs:output_type -> APReplies
	6,  // 11: Wifi.Disconnect:output_type -> google.protobuf.Empty
	3,  // 12: Wifi.Connected:output_type -> ConnectedReply
	6,  // 13: Wifi.Connect:output_type -> google.protobuf.Empty
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_wifi_proto_init() }
func file_wifi_proto_init() {
	if File_wifi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wifi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wifi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APReplies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wifi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Network); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wifi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectedReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wifi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wifi_proto_goTypes,
		DependencyIndexes: file_wifi_proto_depIdxs,
		MessageInfos:      file_wifi_proto_msgTypes,
	}.Build()
	File_wifi_proto = out.File
	file_wifi_proto_rawDesc = nil
	file_wifi_proto_goTypes = nil
	file_wifi_proto_depIdxs = nil
}
