// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DSEnable(arg1, arg2) {
  return window['go']['backend']['Backend']['DSEnable'](arg1, arg2);
}

export function DSGet() {
  return window['go']['backend']['Backend']['DSGet']();
}

export function DSSetCorrection(arg1, arg2) {
  return window['go']['backend']['Backend']['DSSetCorrection'](arg1, arg2);
}

export function DSSetName(arg1, arg2) {
  return window['go']['backend']['Backend']['DSSetName'](arg1, arg2);
}

export function DSSetResolution(arg1, arg2) {
  return window['go']['backend']['Backend']['DSSetResolution'](arg1, arg2);
}

export function DSSetSamples(arg1, arg2) {
  return window['go']['backend']['Backend']['DSSetSamples'](arg1, arg2);
}

export function Events() {
  return window['go']['backend']['Backend']['Events']();
}

export function GPIOGet() {
  return window['go']['backend']['Backend']['GPIOGet']();
}

export function GPIOSetActiveLevel(arg1, arg2) {
  return window['go']['backend']['Backend']['GPIOSetActiveLevel'](arg1, arg2);
}

export function GPIOSetState(arg1, arg2) {
  return window['go']['backend']['Backend']['GPIOSetState'](arg1, arg2);
}

export function HeaterEnable(arg1, arg2) {
  return window['go']['backend']['Backend']['HeaterEnable'](arg1, arg2);
}

export function HeatersGet() {
  return window['go']['backend']['Backend']['HeatersGet']();
}

export function ListInterfaces() {
  return window['go']['backend']['Backend']['ListInterfaces']();
}

export function LoadParameters() {
  return window['go']['backend']['Backend']['LoadParameters']();
}

export function NTPGet() {
  return window['go']['backend']['Backend']['NTPGet']();
}

export function NTPSet(arg1) {
  return window['go']['backend']['Backend']['NTPSet'](arg1);
}

export function PTEnable(arg1, arg2) {
  return window['go']['backend']['Backend']['PTEnable'](arg1, arg2);
}

export function PTGet() {
  return window['go']['backend']['Backend']['PTGet']();
}

export function PTSetCorrection(arg1, arg2) {
  return window['go']['backend']['Backend']['PTSetCorrection'](arg1, arg2);
}

export function PTSetName(arg1, arg2) {
  return window['go']['backend']['Backend']['PTSetName'](arg1, arg2);
}

export function PTSetSamples(arg1, arg2) {
  return window['go']['backend']['Backend']['PTSetSamples'](arg1, arg2);
}

export function PhasesDisable() {
  return window['go']['backend']['Backend']['PhasesDisable']();
}

export function PhasesEnable() {
  return window['go']['backend']['Backend']['PhasesEnable']();
}

export function PhasesGetGlobalConfig() {
  return window['go']['backend']['Backend']['PhasesGetGlobalConfig']();
}

export function PhasesGetPhaseConfigs() {
  return window['go']['backend']['Backend']['PhasesGetPhaseConfigs']();
}

export function PhasesGetPhaseCount() {
  return window['go']['backend']['Backend']['PhasesGetPhaseCount']();
}

export function PhasesMoveToNext() {
  return window['go']['backend']['Backend']['PhasesMoveToNext']();
}

export function PhasesSetConfig(arg1, arg2) {
  return window['go']['backend']['Backend']['PhasesSetConfig'](arg1, arg2);
}

export function PhasesSetGlobalGPIO(arg1) {
  return window['go']['backend']['Backend']['PhasesSetGlobalGPIO'](arg1);
}

export function PhasesSetPhaseCount(arg1) {
  return window['go']['backend']['Backend']['PhasesSetPhaseCount'](arg1);
}

export function PhasesValidateConfig() {
  return window['go']['backend']['Backend']['PhasesValidateConfig']();
}

export function SaveParameters() {
  return window['go']['backend']['Backend']['SaveParameters']();
}

export function TimeSet(arg1) {
  return window['go']['backend']['Backend']['TimeSet'](arg1);
}

export function WifiAPList() {
  return window['go']['backend']['Backend']['WifiAPList']();
}

export function WifiConnect(arg1, arg2) {
  return window['go']['backend']['Backend']['WifiConnect'](arg1, arg2);
}

export function WifiIsConnected() {
  return window['go']['backend']['Backend']['WifiIsConnected']();
}
