// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NotifyDSConfig() {
  return window['go']['backend']['Events']['NotifyDSConfig']();
}

export function NotifyDSTemperature() {
  return window['go']['backend']['Events']['NotifyDSTemperature']();
}

export function NotifyError() {
  return window['go']['backend']['Events']['NotifyError']();
}

export function NotifyGPIO() {
  return window['go']['backend']['Events']['NotifyGPIO']();
}

export function NotifyGlobalConfig() {
  return window['go']['backend']['Events']['NotifyGlobalConfig']();
}

export function NotifyHeaters() {
  return window['go']['backend']['Events']['NotifyHeaters']();
}

export function NotifyPTConfig() {
  return window['go']['backend']['Events']['NotifyPTConfig']();
}

export function NotifyPTTemperature() {
  return window['go']['backend']['Events']['NotifyPTTemperature']();
}

export function NotifyPhasesConfig() {
  return window['go']['backend']['Events']['NotifyPhasesConfig']();
}

export function NotifyPhasesPhaseConfig() {
  return window['go']['backend']['Events']['NotifyPhasesPhaseConfig']();
}

export function NotifyPhasesPhaseCount() {
  return window['go']['backend']['Events']['NotifyPhasesPhaseCount']();
}

export function NotifyPhasesStatus() {
  return window['go']['backend']['Events']['NotifyPhasesStatus']();
}

export function NotifyPhasesValidate() {
  return window['go']['backend']['Events']['NotifyPhasesValidate']();
}
