// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NotifyDSConfig():Promise<string>;

export function NotifyDSTemperature():Promise<string>;

export function NotifyError():Promise<string>;

export function NotifyGPIO():Promise<string>;

export function NotifyHeaters():Promise<string>;

export function NotifyPTConfig():Promise<string>;

export function NotifyPTTemperature():Promise<string>;

export function NotifyPhasesConfig():Promise<string>;

export function NotifyPhasesPhaseConfig():Promise<string>;

export function NotifyPhasesPhaseCount():Promise<string>;

export function NotifyPhasesStatus():Promise<string>;

export function NotifyPhasesValidate():Promise<string>;
