// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GPIOActiveLevel() {
  return window['go']['backend']['Models']['GPIOActiveLevel']();
}

export function GPIOPhaseConfig() {
  return window['go']['backend']['Models']['GPIOPhaseConfig']();
}

export function GPIOPhaseStatus() {
  return window['go']['backend']['Models']['GPIOPhaseStatus']();
}

export function HeaterPhaseConfig() {
  return window['go']['backend']['Models']['HeaterPhaseConfig']();
}

export function HeaterPhaseStatus() {
  return window['go']['backend']['Models']['HeaterPhaseStatus']();
}

export function MoveToNextConfig() {
  return window['go']['backend']['Models']['MoveToNextConfig']();
}

export function ProcessConfigValidation() {
  return window['go']['backend']['Models']['ProcessConfigValidation']();
}

export function ProcessStatus() {
  return window['go']['backend']['Models']['ProcessStatus']();
}

export function Temperature() {
  return window['go']['backend']['Models']['Temperature']();
}

export function TemperatureErrorCodeEmptyBuffer() {
  return window['go']['backend']['Models']['TemperatureErrorCodeEmptyBuffer']();
}

export function TemperatureErrorCodeInternal() {
  return window['go']['backend']['Models']['TemperatureErrorCodeInternal']();
}

export function TemperatureErrorCodeWrongID() {
  return window['go']['backend']['Models']['TemperatureErrorCodeWrongID']();
}

export function TemperaturePhaseStatus() {
  return window['go']['backend']['Models']['TemperaturePhaseStatus']();
}
