// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gpio} from '../models';
import {process} from '../models';
import {distillation} from '../models';
import {parameters} from '../models';

export function GPIOActiveLevel():Promise<gpio.ActiveLevel>;

export function GPIOPhaseConfig():Promise<process.GPIOPhaseConfig>;

export function GPIOPhaseStatus():Promise<process.GPIOPhaseStatus>;

export function HeaterPhaseConfig():Promise<process.HeaterPhaseConfig>;

export function HeaterPhaseStatus():Promise<process.HeaterPhaseStatus>;

export function MoveToNextConfig():Promise<process.MoveToNextConfig>;

export function ProcessConfigValidation():Promise<distillation.ProcessConfigValidation>;

export function ProcessStatus():Promise<distillation.ProcessStatus>;

export function Temperature():Promise<parameters.Temperature>;

export function TemperaturePhaseStatus():Promise<process.TemperaturePhaseStatus>;
